# Generated by Django 2.2.4 on 2019-12-14 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_owner'),
        ('courses', '0003_auto_20191213_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='answers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizzes.Answer'),
            preserve_default=False,
        ),
    ]
