# Generated by Django 2.2.4 on 2019-12-14 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_quizitem_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizitem',
            name='answers',
        ),
    ]
