# Generated by Django 2.2.4 on 2019-12-14 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_quizitem_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizitem',
            name='course',
        ),
        migrations.RemoveField(
            model_name='quizitem',
            name='module',
        ),
    ]
