# Generated by Django 2.2.4 on 2019-12-14 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191213_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quiztype', to='courses.Course'),
            preserve_default=False,
        ),
    ]
