# Generated by Django 2.2.4 on 2019-12-14 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_quizitem_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizitem',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='courses.Module'),
            preserve_default=False,
        ),
    ]
